Eagle2gle/wealth-marble-frontend

package-lock.json, package.json, src/pages/_app.tsx, src/pages/counter.tsx, src/store/index.ts, src/store/modules/counter.ts, src/store/modules/index.ts
💬 관련 이슈
closes #1 
🤷‍♂️ Description
- Redux 설치
- Redux 예제 작성
=> chore: Redux 설치

.eslintrc.json, package-lock.json
💬 관련 이슈
closes #4 
🤷‍♂️ Description
📷 Screenshots
=> [chore] Eslint가 제대로 작동하지 않는 문제 해결

src/pages/_app.tsx, src/pages/counter.tsx, src/store/index.ts, src/store/modules/counter.ts, src/store/modules/index.ts
> closes #16
> 작업 내용에 대한 설명
- Deprecated된 Redux 관련 코드 업데이트
> 작업 결과물
> PR 전 체크해주세요.
=> [refactor] Redux 코드 업데이트

public/cahootListData.json, src/components/TopFiveList.tsx, src/pages/cahoots/index.tsx, src/pages/index.tsx, tailwind.config.js
> closes #26 
> 작업 내용에 대한 설명
- 빌드 오류 수정
- 사용 중인데 삭제된 mock data 복원
- fetch url 수정
- 누락된 suspense 추가
> 작업 결과물
> PR 전 체크해주세요.
1. 로컬에서 build 이후 실행(`npm run start`) 시 `TypeError: fetch failed` 오류가 발생한다면 node 버전을 16으로 낮춰서 실행해주세요. [관련 글](https://stackoverflow.com/a/75208523)
2. index 페이지("/")를 static page로 생성하는 과정에서 오류가 발생한 것을 확인하고, ssr로 빌드되도록 index 페이지에 `getServerSideProps`를 추가해주었더니 정상적으로 빌드가 되었습니다.
오류 원인은 아직 파악하지 못했습니다.
=> [fix] 웹팩 관련 빌드 에러 해결

.github/workflows/CD.yml, .github/workflows/CI.yml, package-lock.json, package.json
> closes #27 
> 작업 내용에 대한 설명
- CI 설정
- CD 설정
- Oracle Cloud 배포
- 도메인 연결 (http://wealth-marble.kro.kr/)
> 작업 결과물
> PR 전 체크해주세요.
=> [chore] Oracle Cloud 배포

.github/workflows/CD-dev.yml, .github/workflows/CD.yml, package.json
> closes #37 
> 작업 내용에 대한 설명
- dev 브랜치 배포 workflow 작성
- main 브랜치 배포 environment 추가
> 작업 결과물
> PR 전 체크해주세요.
=> [chore] dev 브랜치 배포 자동화

.github/workflows/CI.yml, next.config.js, src/components/cahoot/DetailHeader.tsx, src/components/cahoot/DetailInfo.tsx, src/components/cahoot/OrderMobile.tsx, src/pages/api/mock/infinite-cahoot.ts, src/types/cahoot.d.ts
> closes #39 
> 작업 내용에 대한 설명
- description 오타 수정
- 마감된 공모 주문 못하도록 수정
- API 서버 도메인 환경 변수로 분리
> 작업 결과물
> PR 전 체크해주세요.
`.env` 파일에 `SERVER_DOMAIN=http://43.201.148.129:8080`을 추가해주세요.
=> [fix] 공모 상세 페이지 수정

src/pages/index.tsx
> closes #44 
> 작업 내용에 대한 설명
- 메인 페이지 hydration 오류 해결
> 작업 결과물
> PR 전 체크해주세요.
머지하실 때 #43 먼저 머지해 주세요!
=> [bug] 메인 페이지 hydration 오류

src/components/common/Icons.tsx, src/components/market/PriceInfo.tsx, src/components/market/PriceInfoItem.tsx, src/components/market/PriceInfoUpdate.tsx, src/pages/api/mock/markets/price.ts, src/pages/markets/index.tsx, src/utils/date.ts
> closes #52 
> 작업 내용에 대한 설명
- 가격 정보 컴포넌트 구현
> 작업 결과물
<div align="center">
</div>
> PR 전 체크해주세요.
=> [style] 마켓 페이지 - 가격 정보

src/components/cahoot/DeadlineBanner.tsx, src/pages/api/mock/cahoots/mini.ts, src/types/cahoot.d.ts
> closes #53
> 작업 내용에 대한 설명
- 오늘 마감 임박 mock api 추가
- 오늘 마감 임박 슬라이드 애니메이션 추가
> 작업 결과물
무한 슬라이드로 구현하기 위해서 daisyUI의 carousel 대신 `transform: translateY()`를 사용하여 구현하였습니다.
> PR 전 체크해주세요.
#60 PR 먼저 머지 후 브랜치를 삭제하고 머지해 주세요!
=> [feat] 오늘 마감 임박 슬라이드 애니메이션

src/components/cahoot/BuyButton.tsx, src/components/cahoot/DeadlineCarousel.tsx, src/components/cahoot/DetailHeader.tsx, src/components/cahoot/DetailInfo.tsx, src/components/cahoot/InterestButton.tsx, src/components/cahoot/ListItems.tsx, src/components/cahoot/Recap.tsx, src/pages/api/mock/infinite-cahoot.ts, src/pages/cahoots/detail/[id].tsx, src/types/cahoot.d.ts
> closes #58 
> 작업 내용에 대한 설명
- 변경된 query(offset -> page) 반영
- 북마크 여부 반영
- 이미지가 있을 때만 렌더링하도록 수정
> 작업 결과물
> PR 전 체크해주세요.
=> [fix] 공모 검색 API 변경사항 반영

package-lock.json, package.json, src/components/PlaceSearchBar.tsx, src/components/RecommendedList.tsx, src/components/common/DateRangeInput.tsx, src/components/common/Icons.tsx, src/components/common/ImageUpload.tsx, src/components/common/NumberInput.tsx, src/components/common/SelectBox.tsx, src/components/common/TextArea.tsx, src/components/common/TextInput.tsx, src/pages/cahoots/create.tsx
> #51
> 작업 내용에 대한 설명
1. 장소 검색(`PlaceSearchBar.tsx`) 컴포넌트
2. 공모 생성 페이지 
> 작업 결과물
사용자의 특정 동작(ex. 이미지 삭제) 이후 입력값에 대한 유효성 검사를 다시 해야하는 경우, 
trigger 함수를 통해 다시 검사하는 코드를 작성했습니다.
([react-hook-form 공식문서](https://react-hook-form.com/api/useform/trigger))
```ts
const handleRemoveImage = (index: number) => {
// 중략...
trigger(name);
};
```
> PR 전 체크해주세요.
1. POST 하는 쪽에서 Data가 제대로 안넘어가는데 이유를 찾지 못하고 있습니다..ㅠㅠ
2. 숫자 입력 컴포넌트에서 지정한 범위를 벗어난 입력을 하면 자동으로 경계값으로 바뀌게 했는데, 오히려 불편한거 같죠?? 그냥 빨간 글씨가 뜨는 식으로 바꾸는게 나을까요? 의견이 필요합니다!!
=> [feat] 공모 생성 페이지

.env, next.config.js, package-lock.json, package.json, src/components/SocialLoginBtn.tsx, src/pages/_app.tsx, src/pages/oauth2/redirect.tsx, src/store/index.ts, src/store/modules/index.ts, src/store/modules/user.ts
> closes #67
> 작업 내용에 대한 설명
- userSlice 생성 및 redux-persist 적용
- 로그인 성공 시 유저 정보(jwt, id)를 저장하는 페이지 구현
> 작업 결과물
- 로그인 화면
- 로그인 이후 local storage에 저장된 상태
로그인 성공 시 백엔드에서 `http://localhost:3000/oauth2/redirect?token=...`로 리다이렉트가 진행됩니다.
따라서 `page/oauth2/redirect.tsx`에서 query로 전달된 token을 받아서 redux 상태에 저장하고 home으로 리다이렉트 되도록 구현했습니다.
서버사이드에서 query로 온 token을 검증하고 유효하지 않은 경우 notFound 페이지로 리다이렉트 하도록 하고, 유효한 경우 token과 id 값을 props로 전달하도록 구현했습니다.
```tsx
export const getServerSideProps: GetServerSideProps<{ token: string; id: number }> = async (
context
) => {
const { token } = context.query;
if (typeof token !== 'string' || !token) return { notFound: true };
try {
const jwtPayload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
return {
props: {
token,
id: …
```
=> [feat] 구글 소셜 로그인 구현

src/components/cahoot/List.tsx, src/components/market/List.tsx, src/components/market/ListItems.tsx, src/constants/market.ts, src/pages/_app.tsx, src/pages/cahoots/index.tsx, src/pages/markets/index.tsx, src/types/market.d.ts
> closes #57 
> 작업 내용에 대한 설명
- 검색 시 스크롤
- 마켓 검색 API 연동
- 목록 UI 일부 수정
> 작업 결과물
`_app.tsx`에 가지고 있는 토큰이 유효하지 않은 경우 로그아웃 처리하는 로직을 작성했습니다.
> PR 전 체크해주세요.
=> [feat] 마켓 검색

src/components/mypage/UserInfo.tsx
> #69
> 작업 내용에 대한 설명
어제 올린 PR에서 까먹고 push를 안한 커밋이 있어서 다시 PR 올립니다..!
> 작업 결과물
> PR 전 체크해주세요.
=> [style] 마이페이지 레이아웃 추가 작업

src/store/modules/user.ts
> closes #83
> 작업 내용에 대한 설명
- user 초기 상태 변경
> 작업 결과물
> PR 전 체크해주세요.
=> [bug] user 상태 관련 오류

next.config.js
> closes #90
> 작업 내용에 대한 설명
- 이미지 remotePatterns 오류 수정
> 작업 결과물
> PR 전 체크해주세요.
=> [bug] 이미지 remotePatterns 오류

src/components/cahoot/DeadlineCarousel.tsx, src/utils/date.ts
> closes #89
> 작업 내용에 대한 설명
- 당일 마감 임박 공모 날짜 수정
> 작업 결과물
> PR 전 체크해주세요.
=> [bug] 당일 마감 공모에 대한 표시 버그

src/components/market/PriceInfo.tsx, src/components/market/PriceInfoItem.tsx, src/components/market/PriceInfoUpdate.tsx, src/types/market.d.ts
> closes #78 
> 작업 내용에 대한 설명
- 가격 정보 API 연동
> 작업 결과물
> PR 전 체크해주세요.
=> [feat] 마켓 페이지 - 가격 정보 API 연동

README.md
#95 
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.
=> [docs] 기술스택 아이콘 추가

src/components/common/GoBackButton.tsx, src/components/mypage/HeaderWithBackButton.tsx, src/pages/cahoots/create.tsx, src/pages/mypage/cahoots.tsx, src/pages/mypage/management.tsx, src/pages/mypage/stocks.tsx, src/pages/mypage/transactions.tsx
> closes #87 
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.
=> [feat] 뒤로가기 구현

src/components/RecentUploadCarousel.tsx, src/components/RecommendedList.tsx, src/components/TopFiveList.tsx, src/components/common/ButtonGroup.tsx, src/components/common/InterestButton.tsx, src/components/common/SelectBox.tsx, src/pages/cahoots/create.tsx, src/types/cahoot.d.ts, src/types/market.d.ts
> closes #28 
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.
=> [feat] 메인페이지 API 연동

.env, package-lock.json, package.json, src/components/market/DetailBody.tsx, src/components/market/OrderBook.tsx, src/components/market/OrderInput.tsx, src/components/market/TradeTab.tsx, src/hooks/useStomp.ts, src/pages/markets/detail/[id].tsx, src/pages/markets/index.tsx, src/store/modules/index.ts, src/store/modules/marketOrder.ts, src/types/market.d.ts, src/utils/date.ts
> closes #94
> 작업 내용에 대한 설명
- 마켓 거래 UI
- 마켓 거래 WebSocket 연동
> 작업 결과물
<div>
</div>
> PR 전 체크해주세요.
정정, 체결은 아직 미완성입니다.
=> [feat] 마켓 거래

src/pages/cahoots/create.tsx
> 긴급 작업
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.
=> fix: 공모 생성 API 요청 URL 변경

src/pages/cahoots/create.tsx
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.
=> fix: 공모 생성 API 헤더에 token 추가

src/components/market/PriceInfoItem.tsx
> closes #121 
> 작업 내용에 대한 설명
- 마켓 가격 정보 소수점 처리
> 작업 결과물
> PR 전 체크해주세요.
=> [fix] 마켓 가격 정보 소수점 처리

src/components/cahoot/DeadlineBanner.tsx
> closes #120 
> 작업 내용에 대한 설명
- 오늘 마감 임박 배너 api 연동
> 작업 결과물
> PR 전 체크해주세요.
=> [feat] 오늘 마감 임박 배너 api 연동

src/components/market/OrderBook.tsx
> closes #118
> 작업 내용에 대한 설명
- 거래 내역이 없는 경우 무한대로 표시되는 오류 수정
> 작업 결과물
> PR 전 체크해주세요.
=> [fix] 마켓 거래 최근 1주일 최고저가 오류 수정

package-lock.json, package.json, src/components/market/DetailBody.tsx, src/components/market/DetailInfo.tsx, src/components/market/DetailStatus.tsx, src/types/market.d.ts, src/utils/date.ts
> #88 
> 작업 내용에 대한 설명
- 원래 차트도 연동해서 한번에 PR에 올리려고 했으나,
백엔드 파트에서 차트 API 오류 해결이 지연되고 있어 지금까지의 작업내역을 먼저 올립니다!
> 작업 결과물
> PR 전 체크해주세요.
=> [feat] 마켓 상세 페이지 시세, 정보 탭 구현

src/pages/_app.tsx, src/pages/cahoots/detail/[id].tsx, src/pages/cahoots/index.tsx, src/pages/index.tsx, src/pages/markets/detail/[id].tsx, src/pages/markets/index.tsx, src/pages/mypage/index.tsx
> closes #104 
> 작업 내용에 대한 설명
- per-page layout 적용
> 작업 결과물
https://user-images.githubusercontent.com/96206089/230030324-a806cba2-313a-49aa-83d1-0c8b44e6c5d1.mov
> PR 전 체크해주세요.
먼저 #128 을 머지하고 브랜치 삭제 후 머지해 주세요!
=> [refactor] per-page layout 적용

package-lock.json, src/components/cahoot/BuyButton.tsx, src/components/cahoot/DetailBody.tsx, src/components/cahoot/DetailHeader.tsx, src/components/cahoot/DetailInfo.tsx, src/components/cahoot/DetailStatus.tsx, src/components/cahoot/OrderMobile.tsx, src/components/common/InterestButton.tsx, src/components/common/SearchList/CahootItems.tsx, src/components/common/SearchList/index.tsx, src/components/home/RecommendedList/Items.tsx, src/pages/_app.tsx, src/pages/cahoots/detail/[id].tsx, src/pages/cahoots/index.tsx, src/pages/index.tsx, src/pages/markets/detail/[id].tsx, src/pages/markets/index.tsx, src/pages/mypage/cahoots.tsx, src/pages/mypage/index.tsx, src/pages/mypage/stocks.tsx, src/pages/mypage/transactions.tsx, src/queries/cahoots.ts, src/store/modules/cahoot/search.ts, src/store/modules/index.ts
> closes #105 
> 작업 내용에 대한 설명
- 공모 목록/상세 api에 userId 쿼리 추가
- 공모 목록 검색어 전역 상태로 분리 (관심 상품 목록에서 버튼 클릭 시 목록에도 반영하기 위함)
- 관심상품 optimistic update 적용
> 작업 결과물
- 1000ms 지연
https://user-images.githubusercontent.com/96206089/230633504-8ce4c221-d0f5-4bd9-a7b3-5be23076d9ca.mov
> PR 전 체크해주세요.
=> [refactor] 관심상품 optimistic update 적용
